### ISSUE TITLE
Mod developers are having problems with missing linker symbols.

### ISSUE THREAD

**Issue by odevices** [odevices/er-301#13]
The current strategy of using app.cpp.swig, core, and teletype to populate the exported symbol table is no where near enough.

**Comment by tmfset** [comment]
Reproduced here https://github.com/odevices/er-301/pull/14

**Comment by odevices** [comment]
https://github.com/odevices/er-301/tree/issue13

Branch issue13 has a set of fixes for this problem.  @tmfset can you please test it?

**Comment by odevices** [comment]
@tmfset  Nevermind, I just realized that I can do it myself. :laughing:
