### ISSUE TITLE
Error: fonts-freefont-ttf when installing dependencies

### ISSUE THREAD

**Issue by graciousgrendel** [odevices/er-301#19]
I have Homebrew installed on my mac, running Catalina 10.15.7 and when trying to install the dependencies I get the following error, I have tried searching for the error, but am unable to locate any troubleshooting tips. Is there an issue with the distribution or is it just me?

```
$ brew install gcc sdl2 sdl2_ttf fftw swig python3 zip fonts-freefont-ttf
Updating Homebrew...
==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 6 formulae.

==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "fonts-freefont-ttf".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
M$ make emu
make: *** No rule to make target `emu'.  Stop.
```

When trying to compile (after error) I get:
```
$ make emu
make: *** No rule to make target `emu'.  Stop.
```

**Comment by odevices** [comment]
Can you reduce that to:

```bash
brew install gcc sdl2 sdl2_ttf fftw swig
make emu
```

**Comment by nexgen91** [comment]
Thank you, that seemed to do a little better, but still no dice :( Here is the error:
```
$ brew install gcc sdl2 sdl2_ttf fftw swig
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 5 formulae.
==> Updated Casks
Updated 5 casks.

==> Downloading https://homebrew.bintray.com/bottles/gmp-6.2.1.catalina.bottle.tar.gz
#=#=#                                                                         
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to homebrew.bintray.com:443 
Error: Failed to download resource "gmp"
Download failed: https://homebrew.bintray.com/bottles/gmp-6.2.1.catalina.bottle.tar.gz
```

**Comment by odevices** [comment]
So at this point it looks like a problem with your homebrew setup, but I'm not sure.  I don't have a macOS machine to test on.  I recommend posting here

https://forum.orthogonaldevices.com/t/er-301-emulator-for-linux-and-macos/5249?u=odevices

  to get help from those who do.

**Comment by graciousgrendel** [comment]
Okay thank you, I figured out one of my issues, I did not have curl installed. Now that is done, I can run the reduced command and it finishes, but the "make emu" still gives the same error. I posted this on the forum as well, thank you again so much for your help! I look forward to the resuming of shipping of ER-301's at some point, so I can finally get one :)
