### ISSUE TITLE
Using 'replace' on mixer units containing Schroeder Allpasses results in a crash.

### ISSUE THREAD

**Issue by stolmine** [odevices/er-301#38]
Reproduced in firmware 0.6.13.

Steps:

1. Insert a mixer, mono or stereo.
2. inside the mixer, insert a sound generating unit. I tested this procedure with Varispeed players using several different samples.
3. After the sound generator, insert a Schroeder Allpass Filter. Incidentally, this will turn any stereo signal at the input into a mono signal at the output (left channel only).
4. Navigate to the top level of the chain and use the replace command to swap the mixer out for its mono or stereo counterpart. I happened upon this bug trying to remedy the stereo to mono issue, but a crash results in either case.
5. The machine freezes while still on the unit selection screen.

**Comment by odevices** [comment]
Ooops.  That unit shouldn't even be in the library yet because it is not finished (hence the experimental category).  

Thank you for the bug report.
