### ISSUE TITLE
Package Mgr: Units count appears to be off

### ISSUE THREAD

**Issue by SuperNiCd** [odevices/er-301#6]
Suspect it is counting category entries in toc.lua as units.  I currently have 6 units and 5 categories in my toc.lua.  Package manager is displaying 11 units.

**Comment by odevices** [comment]
Oh that reminds me!  I'm going to deprecate the inclusion of category entries in the units table.  Instead, you should just add a category field to the unit entry.  Like this:

```lua
local units = {
  {
    title = "Linear Bipolar VCA",
    moduleName = "VCA.LinearBipolar",
    keywords = "modulate",
    category = "Essentials",
    aliases = {
      "LinearVcaUnit"
    }
  }
}
```

This is already supported, I just haven't migrated the existing toc.lua files yet.
