### ISSUE TITLE
New category style in toc.lua doesn't appear to be working (commit 2e9e5b)

### ISSUE THREAD

**Issue by SuperNiCd** [odevices/er-301#7]
Removed old style category entries in toc.lua:

```lua
{category="Synthesizers"},
{title="Amie",moduleName="Amie",keywords="oscillator"}
```

Switch to new inline style:
`{title="Amie",moduleName="Amie",keywords="oscillator",category="Synthesizers"}`

All units following new style appear in a single category at the bottom of the list, with the name of the category being the package name (e.g. Accents).

**Comment by odevices** [comment]
Oops!  When I did my quick test, my brain didn't register that the categories I was seeing were actually package names. :man_facepalming:
