### ISSUE TITLE
emu: can't zoom out with minus key

### ISSUE THREAD

**Issue by bapch** [odevices/er-301#8]
issue : i can zoom in with "equals" key, but i can't zoom out with "minus" key.
I'm using a french keyboard layout. I replaced SDLK_MINUS with SDLK_6 to get it to work.

**Comment by odevices** [comment]
https://github.com/odevices/er-301/commit/9b90ae2969436a0bbe56cea3d1d86feaa12c8142

Could you try this commit please?  After you run the emulator at least once, there will be a config file called 'emu.db' in root of the rear file tree (e.g. ~/.od/rear/emu.db).  Here you can set most of the key mappings.

**Comment by bapch** [comment]
Hi
Same issue, minus key does not zoom out. I changed the mapping to the 6 key.
On an azerty layout, you have to shift to get the numbers, so 6 key is
shift-minus and does not have its own key like on the qwerty layout.
Weirdly, even the keypad minus doesn't work. It's like the libSDL is bound
to the qwerty layout.
Well, if all azerty users have to do is change minus to 6 in emu.db, i call
it good enough :)
Looks like it's libSDL issue : https://github.com/libsdl-org/SDL/issues/3559

**Comment by odevices** [comment]
I've made the key bindings configurable via configuration file.  Please, check the updated README.

**Comment by bapch** [comment]
The issue persists. 
Temporary fix is the same : 
`ZOOM_OUT_KEY 6`

**Comment by odevices** [comment]
That is the intention though?

**Comment by bapch** [comment]
It was not clear to me if using 6 instead of minus was right for you. It is definitely right for me ! 
You can close the issue :)

**Comment by odevices** [comment]
😊 yay!
